spring:
  application:
    name:
      team1-backend-integration
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

shopify:
  api-version: 2025-01

easypost:
  base-url: https://api.easypost.com